# Generated by Django 5.2.17 on 2026-08-21 05:32

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='business/', validators=[apps.core.validators.validate_image_upload])),
                ('favicon', models.ImageField(blank=True, upload_to='business/', validators=[apps.core.validators.validate_image_upload])),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('return_address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=32)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('cin', models.CharField(blank=True, max_length=32)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.staffrole')),
            ],
        ),
    ]
