# Generated by Django 5.2.17 on 2026-08-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(default='received', max_length=40)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
            ],
            options={
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
