# Generated by Django 5.2.17 on 2026-08-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=80)),
                ('awb', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('tracking_url', models.URLField(blank=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='RTORecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=220)),
                ('received_at_warehouse', models.DateTimeField(blank=True, null=True)),
                ('inventory_adjusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rto_record', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='NDRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=220)),
                ('action', models.CharField(default='reattempt', max_length=80)),
                ('status', models.CharField(default='open', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ndr_records', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=40, unique=True)),
                ('carrier', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipments', models.ManyToManyField(related_name='manifests', to='shipping.shipment')),
            ],
        ),
    ]
